### PR TITLE
Update Brazilian Portuguese translations

### PR DESCRIPTION
**Pull request by blryface**
All the new stuff should be translated.

I took a little long due to Internet issues and getting distracted with other random stuff and TikTok lol

### CODE REVIEW

**Comment by blryface** [comment]
what is this check

**Comment by blryface** [comment]
image
its literally done

**Comment by Flatkat** [comment]
Thanks also dw i feel ya w the internet thing, its my daily life. It gets multiple times for me to be able to even just push a commit, update a repo or reload gradle.

**Review by Flatkat — APPROVED** [review]
Thanks blurry!

**Pull request merged**
