### PR TITLE
Remove VehiclesMoveThroughLeaves 

### PR DESCRIPTION
**Pull request by Flatkat**
Remove VehiclesMoveThroughLeaves as it cant be implemented only on the server-side
(Feature is being moved to Melody)
Related to: https://github.com/Team-Symphony/Melody/pull/4 in Melody

### CODE REVIEW

**Comment by MonkaKokosowa** [comment]
You forgot to remove the config setting for it

**Comment by Flatkat** [comment]
oopsie doopsie

**Comment by Flatkat** [comment]
Btw dont merge this yet as we may be able to keep the feature on Harmony with the help of Polymer. Still not sure tho.

**Comment by Flatkat** [comment]
I have been confirmed this isn't possible to be made server side only without major workarounds. Therefore, this is ready to be merged.

**Review by MonkaKokosowa — APPROVED** [review]

**Pull request merged**
