### PR TITLE
added copper bulb delay

### LINKED ISSUE #49: Change the Copper Bulb tick delay back to 1

### PR DESCRIPTION
**Pull request by RandmlyCoding**

### CODE REVIEW

**Comment by Flatkat** [comment]
Everything seems to be in place in this PR! Its pretty late rn but i will test it tomorrow and see if i can get it merged, so i wont oficially review it for now.

**Review by Flatkat — APPROVED** [review]
I see everything ok now 👍

**Comment by Flatkat** [comment]
i think that since i made commits im not enough to merge this branch. once someone else reviews it it will get merged

**Review by MonkaKokosowa — APPROVED** [review]
LGTM 👍

**Comment by Flatkat** [comment]
image
i hate branch protection

**Comment by Flatkat** [comment]
ok should be fixed now

**Review by MonkaKokosowa — APPROVED** [review]
fr fr everyone who's cool is unprotected

**Comment by Flatkat** [comment]
ok so it seems we are gonna need someone else to review aswell :sob:

**Review by TrigamDev — APPROVED** [review]

**Comment by Flatkat** [comment]
PR APPROVED LETSGOOO
(Thanks tri)

**Comment by RandmlyCoding** [comment]
#16

**Pull request merged**
