### PR TITLE
Added itemDespawnTime settings

### LINKED ISSUE #46: Make items despawn slower on lower difficulties
- 20 minutes on Easy
- 10 minutes on Normal
- 5 minutes on Hard

### PR DESCRIPTION
**Pull request by axialeaa**
Separated easy, normal and hard. Easy affects peaceful too. Time values are calculated in seconds and multiplied up to ticks.

### CODE REVIEW

**Comment by Flatkat** [comment]
I think you didn't see I, this actually was on the feature tracker on the mobs tab. Thank you for the contribution! I will check it when I have the time.

**Comment by Flatkat** [comment]
Oh, please move this to the mobs category, to stay consistent with the Feature Tracker.

**Comment by Flatkat** [comment]
oh crap i am on the wrong issue nvm. I'm on GitHub mobile and it sucks lol

**Review by Flatkat — APPROVED** [review]
LGTM

**Review by MonkaKokosowa — APPROVED** [review]

**Pull request merged**
