### PR TITLE
Bottle+8 sculk->experience bottle implementation

### PR DESCRIPTION
**Pull request by xp2-882030kgz010602**
If I remember correctly, this change wasn't accepted or rejected, but it's something I can implement easily so I might as well. If the change gets rejected, just close this pull request.

### CODE REVIEW

**Comment by Flatkat** [comment]
Hi xp3! so nice to see you again! That change is planned for Melody and not Harmony. Please check the feature tracker prior to making a PR.

**Comment by xp2-882030kgz010602** [comment]
> Hi xp3! so nice to see you again! That change is planned for Melody and not Harmony. Please check the feature tracker prior to making a PR.

I read that thing wrong didn't I. Question though: If it works with datapacks, why can't it go into Harmony? Datapacks only need to be installed on the server to work.

**Comment by Flatkat** [comment]
The main reason of the separation between harmony and melody is not only server-side only content (though that's another big advantage of the split), but rather separating the things that are more conservative direct fixes from those that are more like improvements or add something to fill a gap. This is a brief explanation only thought, I would recommend you checking out our discord to get all the information you need, we would be very happy to work with you and see you again around here. :)

**Comment by xp2-882030kgz010602** [comment]
> The main reason of the separation between harmony and melody is not only server-side only content (though that's another big advantage of the split), but rather separating the things that are more conservative direct fixes from those that are more like improvements or add something to fill a gap.

That makes sense, though I don't know if Harmony is still intended to be server-side only.

>This is a brief explanation only thought, I would recommend you checking out our discord to get all the information you need, we would be very happy to work with you and see you again around here. :)

I am currently trying to decide whether or not to engage with this sentence, and if so, how much.

**Comment by Flatkat** [comment]
Hey, wanted to clarify that yes, the goal is to keep Harmony server-side only and also that even if the change proposed in this issue is indeed labeled as "Melody" rn on the feature sheet it may change, since the feature sheet hasn't been properly reviewed yet.

**Comment by xp2-882030kgz010602** [comment]
I guess that if this turns out to be accepted as a melody feature then we can just try to move the pull request over somehow or something.

**Comment by xp2-882030kgz010602** [comment]
> I am currently trying to decide whether or not to engage with this sentence, and if so, how much.

I have finally come up with better words.

Imagine if you and the other staff+founders worked at a comfy maximum security government facility. One day, czfpdf comes in with a cat. For the purpose of this analogy, assume that it's just a cat: It doesn't have a bomb strapped to it and it doesn't have a microphone recording audio, etc. It's just a cat. Despite the fact that the cat technically doesn't have the security clearance to enter the facility, you decide to let it in anyways since it can't do any harm. Now, would you do the same with a mosquito? I think not. It won't cause a security breach either, but it's just annoying and none of you want it in the facility. My big message was me trying to explain why I was the mosquito and not the cat.

**Comment by TrigamDev** [comment]
> > I am currently trying to decide whether or not to engage with this sentence, and if so, how much.
> 
> I have finally come up with better words.
> 
> Imagine if you and the other staff+founders worked at a comfy maximum security government facility. One day, czfpdf comes in with a cat. For the purpose of this analogy, assume that it's just a cat: It doesn't have a bomb strapped to it and it doesn't have a microphone recording audio, etc. It's just a cat. Despite the fact that the cat technically doesn't have the security clearance to enter the facility, you decide to let it in anyways since it can't do any harm. Now, would you do the same with a mosquito? I think not. It won't cause a security breach either, but it's just annoying and none of you want it in the facility. My big message was me trying to explain why I was the mosquito and not the cat.

???????????????????????????????? what??

**Comment by xp2-882030kgz010602** [comment]
> ???????????????????????????????? what??

Excuse the overcomplications. Let me try a different wording: I pointed out that there were multiple issues with me staying in the server revolving around conflict-of-interest.

**Comment by Flatkat** [comment]
> [DELETED COMMENT]

Hi xp2, I'm sorry to communicate you but this is not the place for this kind of discussion. This is a public PR on a GitHub repo and it's meant to stay on topic. Feel free to reach out anyone you may want to talk with about your personal stuff on Discord or other mediums.

**Comment by Flatkat** [comment]
Regarding this PR I don't think this is the proper way to implement the recipe as we wouldn't be able to make it configurable (without an unnecessary workaround) if it is directly into the data folder. I definitely have to dig deeper on what the proper implementation would be but still; I would say to wait until we merge midnightlib branch into main and then add config support for this prior to merge (in the case it didn't have to be completely rewritten from scratch).

**Comment by ww522-cornell** [comment]
> Hi xp2, I'm sorry to communicate you but this is not the place for this kind of discussion. This is a public PR on a GitHub repo and it's meant to stay on topic. Feel free to reach out anyone you may want to talk with about your personal stuff on Discord or other mediums.

Uh...any way that you can nuke all the off-topic comments? You are completely right and I want to clean up the mess.

**Comment by xp2-882030kgz010602** [comment]
> Hi xp2, I'm sorry to communicate you but this is not the place for this kind of discussion. This is a public PR on a GitHub repo and it's meant to stay on topic. Feel free to reach out anyone you may want to talk with about your personal stuff on Discord or other mediums.

Uh...any way that you can nuke all the off-topic comments? You are completely right and I want to clean up the mess.

**Comment by Flatkat** [comment]
Sure! Please contact me privately if possible though and stay safe.

**Comment by xp2-882030kgz010602** [comment]
> Sure! Please contact me privately if possible though and stay safe.

Before I do anything else with respect to you or the project: Are you **absolutely sure** you want me to contact you privately?

**Comment by Flatkat** [comment]
Yeah, i may not respond today as it is late here but dont fear to do so.
Don't pressure yourself or put yourself down.
If you wanna get in touch again with anyone do so, if not dont. As i said before, this is a public GitHub PR, not an IRC chat.

**Pull request closed without merging**
